### ISSUE TITLE
Linking errors on Android 4.4

### ISSUE THREAD

**Issue by ide** [SoftwareMansion/jsc-android-buildscripts#8]
We're seeing some crashes with the new version of JSC:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libjsc.so" needed by "libreactnativejni.so"; caused by cannot locate symbol "signal" referenced by "libjsc.so"...
       at java.lang.Runtime.load(Runtime.java:333)
       at java.lang.System.load(System.java:512)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
       at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:17)
       at com.facebook.react.bridge.NativeMap.(NativeMap.java)
       at com.facebook.react.bridge.Arguments.createMap(Arguments.java:164)
       at host.exp.exponent.gcm.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:77)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Google devices appear to be fine. We're seeing over half of the crashes from Samsung devices, 7% from Asus, 4% from Rockchip, and 4% from Huawei. We're also seeing it crash in Genymotion as well.

**Comment by hey99xx** [comment]
Possibly caused by https://stackoverflow.com/a/28769262
